tcc-013.1
pamellaneco/tcc-nvt-pamella pull request #21
Opened 2023-05-20 10:07 UTC by pamellaneco

Desenvolvi a funcionalidade de edição do perfil de usuário e ajustei para adicionar ao perfil telefone e localidade. Configuração de controller, rotas e views.

2023-05-29 01:10 UTC, edmargomes requested changes

2023-05-29 01:10 UTC, edmargomes commented on app/Http/Controllers/ProfilesController.php
> +
Remover código comentado

2023-05-29 01:10 UTC, edmargomes commented on app/Http/Controllers/ProfilesController.php
> +           // 'user_id' => auth()->user()->id
Remover código comentado

2023-05-29 01:10 UTC, edmargomes commented on app/Http/Controllers/ProfilesController.php
> +
Parar de inserir a quebra de linha após o {

2023-05-29 01:10 UTC, edmargomes commented on app/Http/Controllers/ProfilesController.php
> +
Parar de inserir a quebra de linha antes do }

2023-05-29 01:10 UTC, edmargomes commented on app/Http/Controllers/ProfilesController.php
> +        return view ('listProducersProfiles')->with('usuarios', $usuarios->get());
Todo o codigo incluindo tabelas deverão estar em inglês, somente aquilo que é escrito para o usuário sera em português.

Lembrando que o laravel tem uma estrutura de localization https://laravel.com/docs/10.x/localization (criar uma tarefa para trocar todos os textos ou labels para localization)

2023-05-29 01:10 UTC, edmargomes commented on app/Http/Controllers/ProfilesController.php
> +        $tipoUsuario = "agricultor";
Não é tipo de usuário, é role, dependando da role visualiza um item ou não

Criar uma terefa para utilizar esse plugin: https://filamentphp.com/plugins/althinect-spatie-roles-permissions

2023-05-29 16:27 UTC, pamellaneco commented on app/Http/Controllers/ProfilesController.php
> +        return view ('listProducersProfiles')->with('usuarios', $usuarios->get());
no caso eu altero esse trecho marcado manualmente e crio uma tarefa para ajustar o resto para localization? ou só resolvo essa conversa no review do github? 
@edmargomes

2023-06-04 12:28 UTC, edmargomes approved these changes

2023-06-04 12:28 UTC, merged